"ENV_NAME": "investment"
"LR": 5e-4
"NUM_ENVS": 2
"NUM_STEPS": 10
"TOTAL_TIMESTEPS": 1e5
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 2
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.3
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.01
"VF_COEF": 1.0
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "tanh"
"ANNEAL_LR": True
"SEED": 42

# WandB Params
"ENTITY": ""
"PROJECT": "jaxmarl-investment"
"WANDB_MODE" : "disabled"

# Investment params
"num_rounds": 5
"num_games": 100
"v_0": 1
"w_0": 1
"v_1": 1
"w_1": 1
"tail": 2
"experiment_name": "sanity"